### ISSUE TITLE
Stop an ffmpeg process

### ISSUE THREAD

**Issue by busla** [Ch00k/ffmpy#11]
Would be great to see an implementation of a class method to kill the process gracefully (with 'q').

I´m trying to stop the ffmpeg process by killing it with SIGINT. Here is a stripped down code of my threading class:

``` python
    def is_process_running(self, process_name):
        p = subprocess.Popen(['ps', '-A'], stdout=subprocess.PIPE)
        out, err = p.communicate()    

        for line in out.splitlines():
            if bytes(process_name, 'utf-8') in line:
                pid = line.split()[0]
                return pid
        return False

    def kill_process(self):
        logger.info('Stopping FFMPEG')
        proc = is_process_running('ffmpeg')
        if proc:
            os.kill(proc, signal.SIGINT)
```

Here is the traceback:

```
Exiting normally, received signal 2.
Exception in thread ffmpeg-thread:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "observer.py", line 45, in run
    self.ff_stream.run()
  File "/Users/levy/Code/streampimp/venv/lib/python3.5/site-packages/ffmpy.py", line 104, in run
    raise FFRuntimeError(self.cmd, ff_command.returncode, out[0], out[1])
ffmpy.FFRuntimeError: `ffmpeg -re -i [the-input-output-parameters]` exited with status 255
```

I´m curious to know how you are dealing with stopping ffmpeg. Note that I´m running ffmpeg in a separate thread.

**Comment by Ch00k** [comment]
This behaviour is actually expected. If you kill ffmpeg process it will exit with code 255 (easily reproducible in the terminal).
I don't think introducing a method to kill the process is a good idea though. Perhaps it's best to leave this to be dealt with by the user. What you could do in this case is catch the exception and check its `exit_code` attribute and ignore the exception based on its value.

**Comment by busla** [comment]
I need to kill it from script since I am recording an hls stream and starting/stopping it according to a schedule.

The resulting mp4s are fine, just thought that it might be another way to handle it.

Sending "q" to stdin maybe.

**Comment by Ch00k** [comment]
Sorry for taking so long to respond. I understand your use case. Would it help if you had access to the underlying subprocess so you could actually call `terminate()` on it?

**Comment by Ch00k** [comment]
@busla I made this change in version 0.2.2. You can now call `terminate()` on `FFmpeg.process` from another thread to terminate the process forcefully.

**Comment by busla** [comment]
Thanks for taking this into consideration, I appreciate it. Will give it a shot!

**Comment by busla** [comment]
This works great!

Running ffmpeg in multiple Class instances now and calling .terminate() on any of them based on timed input.

Beautiful!

**Comment by Jerther** [comment]
Got here from Google and I thought I'd add some side note. So, in its simplest form, this will work with Thread but not Process because Process uses a separate memory space so from outside, ff.process stays None. And also, here's an example for posterity ;)

```
import ffmpy
import time
from threading import Thread

ff = ffmpy.FFmpeg(**snip!**)
process = Thread(target=ff.run)
process.start()
sleep(10)
self.ff.process.terminate()
```

**Comment by imperialguy** [comment]
@Jerther Jerther, this is not working. And why is `self` in there? Did you mean `ff.process.terminate()` instead of `self.ff.process.terminate()` ?

Either way, it throws a threading exception and the recording I am doing doesn't get saved to disk.

**Comment by imperialguy** [comment]
Please help!!!!!!

Here's the code:

`from threading import Thread
import ffmpy

recorder = ffmpy.FFmpeg(*recording params*)
# ffmpy.cmd = fmpeg -f gdigrab -s 1920x1080 -framerate 15 -i desktop rec001.mp4
#
mp_job = Thread(target=recorder.run)
mp_job.start()

**do something here**

recorder.process.terminate()`

And here's the error:

`
Exception in thread Thread-66:
Traceback (most recent call last):
  File "C:\Users\nbkpd02\Programs\python2713-amd64\Lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Users\nbkpd02\Programs\python2713-amd64\Lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "build\bdist.win-amd64\egg\ffmpy.py", line 105, in run
    raise FFRuntimeError(self.cmd, self.process.returncode, out[0], out[1])
FFRuntimeError: `fmpeg -f gdigrab -s 1920x1080 -framerate 15 -i desktop rec001.mp4` exited with status 1

STDOUT:


STDERR:


`

**Comment by Jerther** [comment]
@imperialguy I've updated my comment. You're right, an exception is raised and it is expected. However, in your case, the exit code is 1. I'm not sure but this could indicate a real problem not necessarily related to ffmpy or Thread cancelation.

**Comment by imperialguy** [comment]
The status code 1 happened because of the input parameters. I was manually setting `_cmd` and `cmd` values to a string for testing purposes. So, I made sure to send them as a list now. But, now the status code is returned as 2.

The exact same command runs absolutely fine when I run it on the command line. But, when I do it through python, it returns status code 2. The one difference I noticed is the way the recording is being done:

In python
```
frame=  119 fps= 29 q=28.0 size=       0kB time=00:00:02.40 bitrate=   0.2kbits/s speed=0.594x
```

In plain command line
```
frame=  294 fps= 26 q=-1.0 Lsize=     528kB time=00:00:11.64 bitrate= 371.7kbits/s speed=1.03x
```

With the same exact command running, the way the recording is happening is very different. It looks like the python version has very bad quality. Is it possible that this is happening because of running it inside a python thread? And perhaps, that's why it's exiting with a status code 2. Because as we can see above, bitrate is awful and so is the speed -- so basically nothing is getting recording.

**Comment by andreguilhon** [comment]
@imperialguy Are you using Windows? I'm having the same issue here, and believe the problem is that windows does not allow one to kill a process that doesn't have a window gracefully. We would have to send 'q' to stdin, but as I try to do that, it gives me an error that the file is closed. 
I'm trying to figure this out, and if I have any luck, I'll let you know.

**Comment by onlyet** [comment]
@andreguilhon  bro, do you resolve this question?

**Comment by andreguilhon** [comment]
@onlyet No. I ended up building powershell scripts for the purpose i needed...

**Comment by tbergeron** [comment]
@andreguilhon I'm having the same issue on Windows. What used to work on Linux now simply doesn't on Windows since it's too dumb to gracefully kill windowless PIDs... So I guess I'll run the same code on Linux to get it right. Anyone aware of a real way of gracefully killing a process? I use taskkill.exe and it simply kills ffmpeg without notice so ffmpeg cannot finish whatever it has to do and simply get killed right in the middle of its job.

**Comment by andreguilhon** [comment]
Ok, I had completely forgot about this issue. Windows really is dumb enough so that it is not able to gracefully kill a windowless PID. 
What I did was to use VLC for a while, as it allows you to use a local connection to stop it. VLC uses way too much CPU. That might be a problem. 
Afterwards, I can now use python to send a 'q' to the process. So I use ffmpeg, and send the letter q when I want to end the recording.

**Comment by tbergeron** [comment]
> Afterwards, I can now use python to send a 'q' to the process. So I use ffmpeg, and send the letter q when I want to end the recording.

That's actually a good idea. Still a workaround but that might work in my case as well. Thanks!

**Comment by L05** [comment]
Was able to use the above suggestions to make this work for me:
```
import ffmpy
import time
from threading import Thread
import subprocess

ff = ffmpy.FFmpeg(
    inputs={'in.mp4': None},
    outputs={'out.mp4' : '-t 10'}
)

def execute():
    try:
        ff.run(input_data=subprocess.PIPE)
    except ffmpy.FFRuntimeError as ex:
        if ex.exit_code and ex.exit_code != 255:
            raise
    return

if __name__ == '__main__':
    process = Thread(target=execute)
    process.start()
    time.sleep(7)
    ff.process.communicate(str.encode('q'))
```

You need to pass `input_data=subprocess.PIPE` into run() so that you can send the encoded 'q' keystroke later on.

**Comment by L05** [comment]
It should be noted that the above code will still throw an error (though it will technically work).

A more correct way to do this would be:

```
import ffmpy
from threading import Thread
import subprocess, time, signal, os

ff = ffmpy.FFmpeg(
    inputs={'in.mp4': None},
    outputs={'out.mp4' : None}
)

def execute():
    try:
        ff.run(creationflags=subprocess.CREATE_NEW_PROCESS_GROUP)
    except ffmpy.FFRuntimeError as ex:
        if ex.exit_code and ex.exit_code != 255:
            raise
    return

if __name__ == '__main__':
    process = Thread(target=execute)
    process.start()
    time.sleep(7)
    os.kill(self.ff.process.pid, signal.CTRL_BREAK_EVENT)
```

BUT this would require ffmpy.py to be updated so that line 63 is:
`    def run(self, input_data=None, stdout=None, stderr=None, env=None, creationflags=None):`

and lines 93-95 are:
```
            self.process = subprocess.Popen(
                self._cmd, stdin=subprocess.PIPE, stdout=stdout, stderr=stderr, env=env, creationflags=creationflags
            )
```

These changes have been submitted as Pull Request #55:
https://github.com/Ch00k/ffmpy/pull/55
